jobs:
  build:
    # Variable expansion in working_directory not supported at this time
    # You will need to modify the code below to reflect your github account/repo setup
    working_directory: github.com/Rubtsov1-VO/Kube
    docker:
      - image: node:10-alpine
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker
      
      - run:
          name: Build application container
          command: |
            docker build -t Rubtsov1-VO/Kube .;
      

