  
jobs:
  build:
    # Variable expansion in working_directory not supported at this time
    # You will need to modify the code below to reflect your github account/repo setup
    working_directory: /go/src/github.com/Rubtsov1-VO/rubtsov
    docker:
      - image: circleci/golang:1.8
    environment:
      GO15VENDOREXPERIMENT: 1
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker

      - run: echo 'export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"' >> $BASH_ENV
      - run: echo 'export GOPATH_BASE="${GOPATH_HEAD}/src/github.com/${CIRCLE_PROJECT_USERNAME}"' >> $BASH_ENV
      - run: echo 'export DOCKER_REPO="$(if [ ${CIRCLE_PROJECT_USERNAME} == 'Rubtsov1-VO' ]; then echo vladimir77726; else echo $DOCKER_USER; fi)"' >> $BASH_ENV
      - run: mkdir -p "${GOPATH_BASE}"
      - run: mkdir -p "${GOPATH_HEAD}/bin"
      - run: go get github.com/govend/govend

      - run:
          name: Build application container
          command: |
            
            docker build -t ${DOCKER_REPO}/Kube .;
      

